cloudera-primary-node:
  ports:
  - 7180:7180/tcp
  labels:
    io.rancher.sidekicks: cloudera-primary-node-conf
    io.rancher.container.pull_image: always
    io.rancher.container.dns: 'false'
  command:
  - /sbin/init
  tty: true
  image: reg.index.com/cloudera/primary:v1.0.0
  privileged: true
  volumes:
  - /etc/localtime:/etc/localtime
  stdin_open: true
cloudera-secondary-node-conf:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  image: reg.index.com/cloudera/secondary-conf:v1.0.0
  links:
  - cloudera-dns:cloudera-dns
cloudera-secondary-node:
  labels:
    io.rancher.sidekicks: cloudera-secondary-node-conf
    io.rancher.container.pull_image: always
    io.rancher.container.dns: 'false'
  command:
  - /sbin/init
  tty: true
  image: reg.index.com/cloudera/primary:v1.0.0
  links:
  - cloudera-dns:cloudera-dns
  privileged: true
  volumes:
  - /etc/localtime:/etc/localtime
  stdin_open: true
cloudera-primary-node-conf:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  image: reg.index.com/cloudera/primary-conf:v1.0.0
cloudera-dns-updater:
  environment:
    RFC2136_HOST: cloudera-dns
    RFC2136_PORT: '53'
    RFC2136_TSIG_KEYNAME: sys
    RFC2136_TSIG_SECRET: eBUElyB73+5+8HlE13UJGQ==
    ROOT_DOMAIN: emc
    TTL: '254'
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: external-dns
  command:
  - -provider
  - rfc2136
  image: reg.index.com/cloudera/cloudera-dns-updater:v1.0.0
  links:
  - cloudera-dns:cloudera-dns
cloudera-dns:
  environment:
    BIND9_FORWARDERS: 114.114.114.114;8.8.8.8;
    BIND9_KEY: eBUElyB73+5+8HlE13UJGQ==
    BIND9_KEYNAME: sys
    BIND9_ROOTDOMAIN: emc
    RANCHER_ENV: 'true'
  image: reg.index.com/cloudera/docker-bind9:v1.2.0
